apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator
  labels:
    app: generator
spec:
  replicas: 2 # 데이터 생성 부하 분산을 위해 2개의 복제본 유지, 사용량에 따라서 조정 가능
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - name: generator
        image: event-generator:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: generator-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: generator-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: generator-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: generator-secret
              key: DB_PASSWORD
        resources: # 컨테이너 리소스 제한 설정, 현재 작은 프로젝트 단위이므로 제한 설정 하였음
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
